#!/usr/bin/env ruby

require_relative "../lib/hydrofetch"

require 'sinatra/base'

$scraper = Hydrofetch::Scraper.new(ENV["HYDRO_USER"], ENV["HYDRO_PASS"])

class HydrofetchWeb < Sinatra::Base
  access_logger = ::Logger.new($stdout)

  configure do
    use ::Rack::CommonLogger, access_logger
  end

  before {
    env["rack.errors"] =  $stdout
    content_type 'application/json'
  }

  get('/') do
    JSON.pretty_generate($scraper.one_day_ago)
  end

  get('/report') do
    JSON.pretty_generate($scraper.report)
  end
end

if ARGV[0] == "server"
  HydrofetchWeb.run!(port: 8080)
else
  puts JSON.pretty_generate($scraper.one_day_ago)
end
