---
name: "Build and deploy site"
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # https://github.com/cachix/install-nix-action/issues/56#issuecomment-1240991760
      # - name: "Cache Nix store"
      #   uses: actions/cache@v3.0.8
      #   id: nix-cache
      #   with:
      #     path: /tmp/nixcache
      #     key: "FIXME: Pick a cache key suitable for your use case"
      - name: "Install Nix"
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # - name: "Import Nix store cache"
      #   if: "steps.nix-cache.outputs.cache-hit == 'true'"
      #   run: "nix-store --import < /tmp/nixcache"
      - run: |
          bin/build_image.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if: github.ref == 'refs/heads/main'
      # - name: "Export Nix store cache"
      #   if: "steps.nix-cache.outputs.cache-hit != 'true'"
      #   run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
